# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wydania', models.DateField()),
                ('sygnatura_akt', models.CharField(max_length=40)),
                ('nazwa_i_siedziba_sadu_ktory_wydal_wyrok', models.CharField(max_length=100)),
                ('powod', models.CharField(max_length=100)),
                ('pozwani', models.CharField(max_length=100)),
                ('postanowienie_wzorca', models.TextField()),
                ('data_dokonania_wpisu', models.DateField()),
                ('uwagi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClauseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoundClause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_data', models.TextField()),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Clause')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128)),
                ('clauses', models.ManyToManyField(through='api.FoundClause', to='api.Clause')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
        ),
        migrations.AddField(
            model_name='foundclause',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
        migrations.AddField(
            model_name='clause',
            name='branza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClauseCategory'),
        ),
    ]
