# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160925_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
        ),
    ]
