# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160925_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(max_length=128),
        ),
    ]
